#! /bin/bash

chmod 777 /dev/my_driver

# sleep 2

for (( ; ; ))
do
echo "writing .. fn"
echo sh > /dev/my_driver

sleep 2

echo "reading .. fn"
cat < /dev/my_driver

sleep 2
done

# echo "writing .. fn"
# echo sh > /dev/my_driver

# sleep 2

# echo "reading .. fn"
# cat < /dev/my_driver
